// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_ak9BrMznyz4GpbmAf5dHqqXKquWr1Hg',
    appId: '1:436051843099:web:fc8faa883f2c4362e080be',
    messagingSenderId: '436051843099',
    projectId: 'assignment-25-9a446',
    authDomain: 'assignment-25-9a446.firebaseapp.com',
    storageBucket: 'assignment-25-9a446.firebasestorage.app',
    measurementId: 'G-GCKBZYWFXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjoWaXNT5VxjBbDzrK8op14bcbp0sBbdQ',
    appId: '1:436051843099:android:467c4b2afb378a01e080be',
    messagingSenderId: '436051843099',
    projectId: 'assignment-25-9a446',
    storageBucket: 'assignment-25-9a446.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_ak9BrMznyz4GpbmAf5dHqqXKquWr1Hg',
    appId: '1:436051843099:web:a9661c0500e3b37be080be',
    messagingSenderId: '436051843099',
    projectId: 'assignment-25-9a446',
    authDomain: 'assignment-25-9a446.firebaseapp.com',
    storageBucket: 'assignment-25-9a446.firebasestorage.app',
    measurementId: 'G-MPXF9603MB',
  );
}
